# Generated by Django 5.1.7 on 2025-04-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendar',
            table='calendar',
        ),
    ]
