# Generated by Django 5.1.7 on 2025-04-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('path', models.ForeignKey(db_column='path', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='files.file')),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
    ]
