# Generated by Django 5.1.7 on 2025-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EventChat', 'Event Chat'), ('GroupChat', 'Group Chat'), ('PrivateChat', 'Private Chat')], default='PrivateChat', max_length=20)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
    ]
