# Generated by Django 5.1.7 on 2025-04-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Quitamos la dependencia problemática
        # ('accounts', 'users_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.users')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
