name: cultucat_front
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.3.0
  table_calendar: ^3.1.3

  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  google_maps_cluster_manager: ^3.0.0+1
  shared_preferences: ^2.2.2
  go_router: ^10.1.2
  easy_localization: ^3.0.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  html_unescape: ^2.0.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^17.0.0
  intl: any
  geocoding: ^3.0.0
  url_launcher: ^6.2.2
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  image_picker: ^1.0.0
  firebase_performance: ^0.10.1+5
  firebase_dynamic_links: ^6.1.5
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lang/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"