# Generated by Django 5.1.7 on 2025-04-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=15)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('is_invitation', models.BooleanField(default=False)),
                ('idgroup', models.ForeignKey(db_column='idgroup', on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('responded_by', models.ForeignKey(db_column='responded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to='accounts.users')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to='accounts.users')),
            ],
            options={
                'db_table': 'group_request',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('idgroup', 'username', 'status'), name='unique_group_user_request')],
            },
        ),
    ]
