# Generated by Django 5.1.7 on 2025-04-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvent',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eventos.event')),
            ],
            options={
                'db_table': 'categoriaevent',
                'managed': False,
            },
        ),
    ]
