# Generated by Django 5.1.7 on 2025-04-19 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('language', models.CharField(max_length=50)),
                ('telf', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
