# Generated by Django 5.1.7 on 2025-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('path', models.TextField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Document', 'Document')], default='Image', max_length=10)),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
    ]
